(()=>{
  const $=(selector,root=document)=>root.querySelector(selector);
  const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:4});
  const units=[['un','Unidade'],['folha','Folha'],['cm','Centímetro'],['m','Metro'],['g','Grama'],['kg','Quilo'],['ml','Mililitro'],['L','Litro']];
  let materials=[],products=[],editingMaterial=null,composition=[];
  async function headers(){const session=await window.PPAuth.getSession();if(!session?.access_token)throw new Error('Sessão expirada');return{apikey:window.PPAuth.key,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'}}
  async function api(path,options={}){const response=await fetch(`${window.PPAuth.url}/rest/v1/${path}`,{...options,headers:{...(await headers()),...(options.headers||{})}});if(!response.ok)throw new Error(await response.text());if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}
  function install(){const nav=$('#nav'),main=$('.main');if(!nav||!main)return;if(!$('#cost-calculator-nav')){[['cost-calculator-nav','Calculadora','calculator'],['cost-materials-nav','Material','materials'],['cost-composition-nav','Custo','cost']].forEach(([id,label,tab])=>{const button=document.createElement('button');button.id=id;button.type='button';button.className='cost-nav-btn';button.textContent=label;button.onclick=()=>open(tab);nav.appendChild(button)})}if(!$('#view-custos')){const view=document.createElement('section');view.id='view-custos';view.className='view';main.appendChild(view)}}
  async function loadBase(){[materials,products]=await Promise.all([api('materials?select=*&active=eq.true&order=name.asc'),api('products?select=id,name,sku,cost_price&deleted_at=is.null&active=eq.true&order=name.asc')])}
  function tabs(active){return `<div class="cost-tabs"><button data-cost-tab="calculator" class="${active==='calculator'?'active':''}">Calculadora</button><button data-cost-tab="materials" class="${active==='materials'?'active':''}">Material</button><button data-cost-tab="cost" class="${active==='cost'?'active':''}">Custo</button></div>`}
  function bindTabs(host){host.querySelectorAll('[data-cost-tab]').forEach(button=>button.onclick=()=>open(button.dataset.costTab))}
  function showCalculator(){const host=$('#view-custos');host.innerHTML=tabs('calculator')+`<section class="cost-card"><h2>Calculadora</h2><p>Descubra rapidamente o custo por unidade, peso ou metragem.</p><div class="cost-form-grid"><label>Valor pago (R$)<input id="quick-total" type="number" min="0" step="0.01" placeholder="10,00"></label><label>Quantidade do pacote<input id="quick-quantity" type="number" min="0.0001" step="0.0001" placeholder="100"></label><label class="cost-wide">Unidade de medida<select id="quick-unit">${units.map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></label></div><div class="cost-result"><span>Custo por <b id="quick-unit-label">unidade</b></span><strong id="quick-result">R$ 0,00</strong><small>Exemplo: R$ 10,00 ÷ 100 folhas = R$ 0,10 por folha.</small></div></section>`;bindTabs(host);const calculate=()=>{const total=Number($('#quick-total').value||0),quantity=Number($('#quick-quantity').value||0),label=$('#quick-unit').selectedOptions[0].text.toLowerCase();$('#quick-unit-label').textContent=label;$('#quick-result').textContent=money(quantity>0?total/quantity:0)};['#quick-total','#quick-quantity','#quick-unit'].forEach(id=>$(id).addEventListener('input',calculate))}
  function showMaterials(){const host=$('#view-custos'),item=editingMaterial||{};host.innerHTML=tabs('materials')+`<div class="cost-grid"><form id="material-cost-form" class="cost-card"><h2>${editingMaterial?'Editar':'Novo'} material</h2><p>Cadastre o valor da compra e a quantidade recebida. O custo unitário será calculado automaticamente.</p><div class="cost-form-grid"><label class="cost-wide">Nome do material<input id="material-name" required value="${esc(item.name||'')}" placeholder="Ex.: Papel offset A4"></label><label>Valor pago (R$)<input id="material-purchase" required type="number" min="0" step="0.01" value="${Number(item.purchase_price||0)}"></label><label>Quantidade, peso ou metragem<input id="material-package" required type="number" min="0.0001" step="0.0001" value="${Number(item.package_quantity||1)}"></label><label>Unidade de medida<select id="material-unit">${units.map(([value,label])=>`<option value="${value}" ${item.unit===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Estoque atual<input id="material-stock" type="number" min="0" step="0.0001" value="${Number(item.stock??item.package_quantity??0)}"></label><label class="cost-wide">Fornecedor (opcional)<input id="material-supplier" value="${esc(item.supplier||'')}"></label></div><div class="cost-result"><span>Custo calculado por unidade</span><strong id="material-unit-cost">${money(item.cost_per_unit||0)}</strong></div><div class="cost-actions">${editingMaterial?'<button id="material-cancel" type="button" class="button secondary">Cancelar</button>':''}<button class="button primary">Salvar material</button></div><div id="material-status" class="cost-status"></div></form><section class="cost-card"><h2>Materiais cadastrados</h2><p>Valores usados automaticamente na composição dos produtos.</p><div id="material-list">${materials.length?materials.map(material=>`<article class="material-row"><div><b>${esc(material.name)}</b><small>${Number(material.package_quantity||0)} ${esc(material.unit)} por ${money(material.purchase_price||0)}</small></div><div class="material-cost">${money(material.cost_per_unit)}<small>por ${esc(material.unit)}</small></div><button type="button" class="button secondary" data-edit-material="${material.id}">Editar</button></article>`).join(''):'<div class="cost-empty">Nenhum material cadastrado.</div>'}</div></section></div>`;bindTabs(host);const calc=()=>{$('#material-unit-cost').textContent=money(Number($('#material-purchase').value||0)/Number($('#material-package').value||0))};$('#material-purchase').oninput=calc;$('#material-package').oninput=calc;$('#material-cancel')?.addEventListener('click',()=>{editingMaterial=null;showMaterials()});host.querySelectorAll('[data-edit-material]').forEach(button=>button.onclick=()=>{editingMaterial=materials.find(material=>material.id===button.dataset.editMaterial);showMaterials()});$('#material-cost-form').onsubmit=saveMaterial}
  async function saveMaterial(event){event.preventDefault();const purchase=Number($('#material-purchase').value||0),quantity=Number($('#material-package').value||0);if(quantity<=0)return $('#material-status').textContent='Informe uma quantidade maior que zero.';const payload={name:$('#material-name').value.trim(),purchase_price:purchase,package_quantity:quantity,unit:$('#material-unit').value,cost_per_unit:Number((purchase/quantity).toFixed(6)),stock:Number($('#material-stock').value||0),supplier:$('#material-supplier').value.trim()||null,active:true,updated_at:new Date().toISOString()};if(editingMaterial)await api(`materials?id=eq.${editingMaterial.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)});else await api('materials',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({...payload,min_stock:0})});editingMaterial=null;await loadBase();showMaterials()}
  function compositionTotals(){let cost=0;for(const row of composition){const material=materials.find(item=>item.id===row.material_id);if(!material)continue;cost+=Number(material.cost_per_unit||0)*Number(row.quantity||0)*(1+Number(row.waste||0)/100)}const margin=Math.min(95,Math.max(0,Number($('#cost-margin')?.value||0)));return{cost,sale:cost/(1-margin/100)}}
  function updateComposition(){const totals=compositionTotals();$('#composition-total').textContent=money(totals.cost);$('#composition-sale').textContent=money(totals.sale);$('#composition-count').textContent=`${composition.filter(row=>row.material_id&&row.quantity>0).length} material(is)`}
  function drawRows(){const box=$('#composition-rows');box.innerHTML=composition.length?composition.map((row,index)=>`<div class="composition-row"><label>Material<select data-material="${index}"><option value="">Selecione</option>${materials.map(material=>`<option value="${material.id}" ${row.material_id===material.id?'selected':''}>${esc(material.name)} — ${money(material.cost_per_unit)}/${esc(material.unit)}</option>`).join('')}</select></label><label>Quantidade usada<input data-quantity="${index}" type="number" min="0.0001" step="0.0001" value="${row.quantity||1}"></label><label>Perda %<input data-waste="${index}" type="number" min="0" max="100" step="0.1" value="${row.waste||0}"></label><button type="button" class="button secondary" data-remove="${index}">×</button></div>`).join(''):'<div class="cost-empty">Adicione os materiais utilizados neste produto.</div>';box.querySelectorAll('[data-material]').forEach(input=>input.onchange=()=>{composition[+input.dataset.material].material_id=input.value;updateComposition()});box.querySelectorAll('[data-quantity]').forEach(input=>input.oninput=()=>{composition[+input.dataset.quantity].quantity=Number(input.value||0);updateComposition()});box.querySelectorAll('[data-waste]').forEach(input=>input.oninput=()=>{composition[+input.dataset.waste].waste=Number(input.value||0);updateComposition()});box.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{composition.splice(+button.dataset.remove,1);drawRows()});updateComposition()}
  function showCost(){const host=$('#view-custos');host.innerHTML=tabs('cost')+`<section class="cost-card"><div class="composition-head"><div><h2>Custo do produto</h2><p>Escolha os materiais e informe quanto será utilizado em uma unidade do produto.</p></div><button id="composition-add" type="button" class="button secondary">+ Material</button></div><div class="cost-form-grid"><label>Produto cadastrado<select id="cost-product"><option value="">Simulação sem salvar</option>${products.map(product=>`<option value="${product.id}">${esc(product.name)}${product.sku?` — ${esc(product.sku)}`:''}</option>`).join('')}</select></label><label>Margem desejada (%)<input id="cost-margin" type="number" min="0" max="95" step="0.1" value="50"></label></div><div id="composition-rows" style="margin-top:14px"></div><div class="composition-summary"><div><span>Materiais utilizados</span><strong id="composition-count">0</strong></div><div><span>Custo total de material</span><strong id="composition-total">R$ 0,00</strong></div><div class="sale"><span>Preço sugerido com margem</span><strong id="composition-sale">R$ 0,00</strong></div></div><p class="cost-note">O preço sugerido considera somente o custo dos materiais e a margem escolhida. Frete, impostos e outras despesas podem ser acrescentados no orçamento.</p><div class="cost-actions"><button id="composition-save" type="button" class="button primary" disabled>Salvar custo no produto</button></div><div id="composition-status" class="cost-status"></div></section>`;bindTabs(host);composition=[];$('#composition-add').onclick=()=>{composition.push({material_id:'',quantity:1,waste:0});drawRows()};$('#cost-margin').oninput=updateComposition;$('#cost-product').onchange=loadComposition;$('#composition-save').onclick=saveComposition;drawRows()}
  async function loadComposition(){const productId=$('#cost-product').value;$('#composition-save').disabled=!productId;if(!productId){composition=[];drawRows();return}const links=await api(`product_materials?select=*&product_id=eq.${productId}&order=created_at.asc`);composition=(links||[]).map(link=>({material_id:link.material_id,quantity:Number(link.quantity),waste:Number(link.waste_percent||0)}));drawRows()}
  async function saveComposition(){const productId=$('#cost-product').value,valid=composition.filter(row=>row.material_id&&row.quantity>0);if(!productId)return;await api(`product_materials?product_id=eq.${productId}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});if(valid.length)await api('product_materials',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(valid.map(row=>({product_id:productId,material_id:row.material_id,quantity:row.quantity,waste_percent:row.waste||0})))});const total=compositionTotals().cost;await api(`products?id=eq.${productId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({cost_price:Number(total.toFixed(4)),updated_at:new Date().toISOString()})});$('#composition-status').textContent='Composição e custo salvos no produto ✓';await loadBase();window.PPProducts?.refresh?.()}
  async function open(tab='calculator'){install();document.querySelectorAll('.view').forEach(view=>view.classList.remove('active'));$('#view-custos').classList.add('active');document.querySelectorAll('#nav button').forEach(button=>button.classList.remove('active'));$(`#cost-${tab==='cost'?'composition':tab}-nav`)?.classList.add('active');$('#page-title').textContent=tab==='calculator'?'Calculadora':tab==='materials'?'Material':'Custo';$('#page-subtitle').textContent=tab==='calculator'?'Calcule rapidamente o custo por unidade':tab==='materials'?'Cadastre matérias-primas, quantidades e valores pagos':'Monte produtos com custo real de material';try{await loadBase();if(tab==='calculator')showCalculator();else if(tab==='materials')showMaterials();else showCost()}catch(error){console.error(error);$('#view-custos').innerHTML=`<div class="cost-empty">Não foi possível carregar os custos. Atualize a página e tente novamente.</div>`}}
  document.addEventListener('input',event=>{
    if(event.target?.id==='material-stock')event.target.dataset.touched='true';
    if(event.target?.id==='material-package'&&!editingMaterial){
      const stock=$('#material-stock');
      if(stock&&stock.dataset.touched!=='true')stock.value=event.target.value||'0';
    }
  });
  install();window.BrindesOnCosts={open};
})();
