(()=>{
let products=[];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
async function refresh(){try{const r=await fetch(`${window.PPAuth.url}/rest/v1/products?select=id,name,sku,sale_price,stock&active=eq.true&order=name.asc`,{headers:{apikey:window.PPAuth.key}});if(!r.ok)throw new Error(await r.text());products=await r.json();decorate()}catch(e){console.warn('Preços dos produtos',e)}}
function findProduct(name){const n=String(name||'').trim().toLowerCase();return products.find(p=>String(p.name||'').trim().toLowerCase()===n)||null}
function recalc(){let total=0;document.querySelectorAll('#items-list .item-row').forEach(row=>{const q=Number(row.querySelector('.item-qty')?.value||0),name=row.querySelector('.item-product')?.value||'',p=findProduct(name),priceInput=row.querySelector('.item-unit-price'),line=row.querySelector('.item-line-total');if(p&&priceInput&&!priceInput.dataset.manual)priceInput.value=Number(p.sale_price||0).toFixed(2);const price=Number(priceInput?.value||0),sub=q*price;if(line)line.value=money(sub);total+=sub});const t=document.getElementById('order-total-amount');if(t){t.value=total.toFixed(2);t.readOnly=true;let note=t.parentElement.querySelector('.order-auto-total-note');if(!note){note=document.createElement('small');note.className='order-auto-total-note';note.textContent='Calculado automaticamente pelos itens do pedido';t.parentElement.appendChild(note)}}}
function decorate(){document.querySelectorAll('#items-list .item-row').forEach(row=>{if(row.classList.contains('order-pricing'))return;row.classList.add('order-pricing');const remove=row.querySelector('.remove-item'),pers=row.querySelector('.item-personalization')?.closest('label');if(!remove||!pers)return;const price=document.createElement('label');price.innerHTML='Preço unitário<input class="item-unit-price" type="number" min="0" step="0.01" inputmode="decimal" value="0.00">';const subtotal=document.createElement('label');subtotal.innerHTML='Subtotal<input class="item-line-total" value="R$ 0,00" readonly>';pers.insertAdjacentElement('afterend',price);price.insertAdjacentElement('afterend',subtotal);const product=row.querySelector('.item-product'),qty=row.querySelector('.item-qty'),pi=price.querySelector('input');product?.addEventListener('change',()=>{pi.dataset.manual='';recalc()});product?.addEventListener('input',()=>{pi.dataset.manual='';recalc()});qty?.addEventListener('input',recalc);pi.addEventListener('input',()=>{pi.dataset.manual='1';recalc()})});recalc()}
const observer=new MutationObserver(()=>decorate());
const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init={}){const url=typeof input==='string'?input:input.url;if(url.includes('/rest/v1/order_items')&&init?.method==='POST'&&init.body){try{const body=JSON.parse(init.body);const inject=i=>{const p=findProduct(i.product_name);const price=Number(p?.sale_price||0);return{...i,product_id:p?.id||null,unit_price:price,line_total:Number(i.quantity||0)*price}};init={...init,body:JSON.stringify(Array.isArray(body)?body.map(inject):inject(body))}}catch{}}return nativeFetch(input,init)};
document.addEventListener('DOMContentLoaded',()=>{const items=document.getElementById('items-list');if(items)observer.observe(items,{childList:true,subtree:true});setTimeout(refresh,400);document.addEventListener('click',e=>{if(e.target.closest('.nav-item[data-view="novo"]'))setTimeout(()=>{refresh();decorate()},150)});document.getElementById('order-form')?.addEventListener('reset',()=>setTimeout(recalc,0))});window.PPProductPricing={refresh,recalc};
})();