(()=>{
const $=s=>document.querySelector(s),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],editingId=null;
async function headers(){const s=await window.PPAuth.getSession();if(!s?.access_token)throw new Error('Sessão expirada');return{apikey:window.PPAuth.key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'}}
function ensureUI(){const host=$('#view-produtos');if(!host||host.dataset.ready)return;host.dataset.ready='1';host.innerHTML=`<div class="products-grid"><form id="product-form" class="product-form"><h2>Novo produto</h2><label>SKU / Código<input id="product-sku" placeholder="Ex.: CHV001"></label><label>Nome do produto<input id="product-name" required placeholder="Nome do produto"></label><label>Preço de venda (R$)<input id="product-price" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0,00"></label><label>Estoque<input id="product-stock" type="number" min="0" step="1" value="0"></label><label>Categoria<input id="product-category" placeholder="Ex.: Chaveiros"></label><label>Descrição<textarea id="product-description" rows="3" placeholder="Observações do produto"></textarea></label><div class="product-form-actions"><button id="product-cancel" type="button" class="button secondary hidden">Cancelar edição</button><button type="submit" class="button primary">Salvar produto</button></div></form><section class="product-list-panel"><div class="products-toolbar"><input id="product-search" placeholder="Buscar por nome, SKU ou categoria"><button id="product-refresh" type="button" class="button secondary">Atualizar</button></div><h2>Produtos cadastrados</h2><div id="product-list"></div></section></div>`;$('#product-form').addEventListener('submit',save);$('#product-search').addEventListener('input',render);$('#product-refresh').onclick=()=>load().catch(showError);$('#product-cancel').onclick=reset}
async function load(){const h=await headers();const r=await fetch(`${window.PPAuth.url}/rest/v1/products?select=*&order=name.asc`,{headers:h});if(!r.ok)throw new Error(await r.text());products=await r.json();render();window.PPStandaloneCatalog?.refresh?.();window.PPProductPricing?.refresh?.()}
function render(){const list=$('#product-list');if(!list)return;const q=($('#product-search')?.value||'').trim().toLowerCase();const rows=products.filter(p=>!q||[p.name,p.sku,p.category].some(v=>String(v||'').toLowerCase().includes(q)));list.innerHTML=rows.length?rows.map(p=>`<article class="product-card"><div class="product-card-head"><div><h3>${esc(p.name)}</h3><div class="product-card-meta">${p.sku?`<span>SKU ${esc(p.sku)}</span>`:''}${p.category?`<span>${esc(p.category)}</span>`:''}<span>Estoque ${Number(p.stock||0)}</span></div><div class="product-price">${Number(p.sale_price||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div></div><div class="product-actions"><button class="button secondary product-edit" data-id="${p.id}" type="button">Editar</button><button class="button danger product-delete" data-id="${p.id}" type="button">Excluir</button></div></div></article>`).join(''):'<div class="product-empty">Nenhum produto encontrado.</div>';list.querySelectorAll('.product-edit').forEach(b=>b.onclick=()=>edit(b.dataset.id));list.querySelectorAll('.product-delete').forEach(b=>b.onclick=()=>remove(b.dataset.id))}
function edit(id){const p=products.find(x=>x.id===id);if(!p)return;editingId=id;$('#product-form h2').textContent='Editar produto';$('#product-sku').value=p.sku||'';$('#product-name').value=p.name||'';$('#product-price').value=Number(p.sale_price||0).toFixed(2);$('#product-stock').value=Number(p.stock||0);$('#product-category').value=p.category||'';$('#product-description').value=p.description||'';$('#product-cancel').classList.remove('hidden');$('#product-name').focus()}
function reset(){editingId=null;$('#product-form').reset();$('#product-stock').value='0';$('#product-form h2').textContent='Novo produto';$('#product-cancel').classList.add('hidden')}
async function save(e){e.preventDefault();const payload={sku:$('#product-sku').value.trim()||null,name:$('#product-name').value.trim(),sale_price:Number($('#product-price').value||0),stock:Number($('#product-stock').value||0),category:$('#product-category').value.trim()||null,description:$('#product-description').value.trim()||null,active:true,updated_at:new Date().toISOString(),net_weight:0,gross_weight:0,package_type:'',packaging:'',width_cm:0,height_cm:0,length_cm:0};if(!payload.name)return;const h=await headers(),url=editingId?`${window.PPAuth.url}/rest/v1/products?id=eq.${encodeURIComponent(editingId)}`:`${window.PPAuth.url}/rest/v1/products`;const wasEditing=!!editingId;const r=await fetch(url,{method:wasEditing?'PATCH':'POST',headers:{...h,Prefer:'return=minimal'},body:JSON.stringify(payload)});if(!r.ok){showError(new Error(await r.text()));return}reset();await load();alert(wasEditing?'Produto atualizado.':'Produto salvo com sucesso.')}
async function remove(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`Excluir o produto "${p.name}"?`))return;const h=await headers();const r=await fetch(`${window.PPAuth.url}/rest/v1/products?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:h});if(!r.ok){showError(new Error(await r.text()));return}await load()}
function showError(e){console.error(e);alert('Não foi possível concluir esta ação. Verifique a conexão e tente novamente.')}
function open(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('#view-produtos')?.classList.add('active');document.querySelectorAll('.nav-item,.phase-nav-btn,.customer-nav-btn,.product-nav-btn').forEach(b=>b.classList.remove('active'));$('#products-nav')?.classList.add('active');$('#page-title').textContent='Produtos';$('#page-subtitle').textContent='Cadastro, preço de venda e estoque';ensureUI();load().catch(showError)}
document.addEventListener('DOMContentLoaded',()=>{$('#products-nav')?.addEventListener('click',open);document.querySelectorAll('.nav-item,.phase-nav-btn,.customer-nav-btn').forEach(b=>b.addEventListener('click',()=>$('#products-nav')?.classList.remove('active')))});window.PPProducts={open,refresh:load};
})();