alter table public.products
  add column if not exists production_capacity_per_day numeric not null default 50
  check (production_capacity_per_day > 0);

alter table public.orders
  add column if not exists estimated_completion_date date,
  add column if not exists quality_status text not null default 'pendente'
    check (quality_status in ('pendente','em_conferencia','aprovado')),
  add column if not exists quality_completed_at timestamptz,
  add column if not exists quality_completed_by uuid references auth.users(id),
  add column if not exists public_tracking_token text default encode(gen_random_bytes(32),'hex');

update public.orders
set public_tracking_token = encode(gen_random_bytes(32),'hex')
where public_tracking_token is null;

alter table public.orders alter column public_tracking_token set not null;
create unique index if not exists orders_public_tracking_token_idx
  on public.orders(public_tracking_token);

create table if not exists public.order_quality_checks (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  check_key text not null,
  label text not null,
  completed boolean not null default false,
  note text,
  completed_at timestamptz,
  completed_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id,check_key)
);

create index if not exists order_quality_checks_order_idx
  on public.order_quality_checks(order_id);

create table if not exists public.order_timeline (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  event_type text not null,
  title text not null,
  details jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists order_timeline_order_created_idx
  on public.order_timeline(order_id,created_at desc);

alter table public.order_quality_checks enable row level security;
alter table public.order_timeline enable row level security;

drop policy if exists order_quality_checks_staff_select on public.order_quality_checks;
create policy order_quality_checks_staff_select on public.order_quality_checks
for select to authenticated
using (public.koda_has_role(array['admin','vendas','producao']));

drop policy if exists order_quality_checks_staff_insert on public.order_quality_checks;
create policy order_quality_checks_staff_insert on public.order_quality_checks
for insert to authenticated
with check (public.koda_has_role(array['admin','producao']));

drop policy if exists order_quality_checks_staff_update on public.order_quality_checks;
create policy order_quality_checks_staff_update on public.order_quality_checks
for update to authenticated
using (public.koda_has_role(array['admin','producao']))
with check (public.koda_has_role(array['admin','producao']));

drop policy if exists order_quality_checks_admin_delete on public.order_quality_checks;
create policy order_quality_checks_admin_delete on public.order_quality_checks
for delete to authenticated
using (public.koda_has_role(array['admin']));

drop policy if exists order_timeline_staff_select on public.order_timeline;
create policy order_timeline_staff_select on public.order_timeline
for select to authenticated
using (public.koda_has_role(array['admin','vendas','producao']));

grant select,insert,update,delete on public.order_quality_checks to authenticated;
grant select on public.order_timeline to authenticated;
grant usage,select on sequence public.order_timeline_id_seq to authenticated;
revoke all on public.order_quality_checks from anon;
revoke all on public.order_timeline from anon;
revoke all on sequence public.order_timeline_id_seq from anon;
create index if not exists order_quality_checks_completed_by_idx on public.order_quality_checks(completed_by);
create index if not exists order_timeline_created_by_idx on public.order_timeline(created_by);

create or replace function private.ensure_order_quality_checks(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.order_quality_checks(order_id,check_key,label)
  values
    (p_order_id,'quantity','Quantidade conferida'),
    (p_order_id,'personalization','Personalização conferida'),
    (p_order_id,'finish','Acabamento e qualidade aprovados'),
    (p_order_id,'packaging','Pedido completo e embalagem conferida')
  on conflict(order_id,check_key) do nothing;
end
$$;

create or replace function private.order_quality_defaults()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.ensure_order_quality_checks(new.id);
  return new;
end
$$;

drop trigger if exists trg_order_quality_defaults on public.orders;
create trigger trg_order_quality_defaults
after insert on public.orders
for each row execute function private.order_quality_defaults();

do $$
declare item record;
begin
  for item in select id from public.orders loop
    perform private.ensure_order_quality_checks(item.id);
  end loop;
end
$$;

create or replace function public.koda_set_quality_check(
  p_order_id uuid,
  p_check_key text,
  p_completed boolean,
  p_note text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_total integer;
  v_completed integer;
begin
  if not public.koda_has_role(array['admin','producao']) then
    raise exception 'Acesso negado';
  end if;

  update public.order_quality_checks
  set completed = p_completed,
      note = nullif(trim(coalesce(p_note,'')),''),
      completed_at = case when p_completed then now() else null end,
      completed_by = case when p_completed then auth.uid() else null end,
      updated_at = now()
  where order_id = p_order_id and check_key = p_check_key;

  if not found then raise exception 'Verificação não encontrada'; end if;

  select count(*),count(*) filter(where completed)
  into v_total,v_completed
  from public.order_quality_checks where order_id=p_order_id;

  update public.orders
  set quality_status = case
        when v_total > 0 and v_completed = v_total then 'aprovado'
        when v_completed > 0 then 'em_conferencia'
        else 'pendente' end,
      quality_completed_at = case when v_total > 0 and v_completed = v_total then now() else null end,
      quality_completed_by = case when v_total > 0 and v_completed = v_total then auth.uid() else null end,
      updated_at = now()
  where id = p_order_id;

  return jsonb_build_object('total',v_total,'completed',v_completed,'approved',v_total>0 and v_total=v_completed);
end
$$;

create or replace function public.koda_pack_order(p_order_id uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not public.koda_has_role(array['admin','producao']) then
    raise exception 'Acesso negado';
  end if;
  if exists(select 1 from public.order_quality_checks where order_id=p_order_id and not completed)
     or not exists(select 1 from public.order_quality_checks where order_id=p_order_id) then
    raise exception 'Conclua todas as verificações de qualidade antes de embalar';
  end if;
  update public.orders
  set phase='embalado',status='finalizado',finished_at=coalesce(finished_at,now()),updated_at=now()
  where id=p_order_id and deleted_at is null;
  if not found then raise exception 'Pedido não encontrado'; end if;
end
$$;

grant execute on function public.koda_set_quality_check(uuid,text,boolean,text) to authenticated;
grant execute on function public.koda_pack_order(uuid) to authenticated;
revoke execute on function public.koda_set_quality_check(uuid,text,boolean,text) from public,anon;
revoke execute on function public.koda_pack_order(uuid) from public,anon;

create or replace function private.refresh_order_estimate(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare v_days integer;
begin
  select greatest(1,ceil(coalesce(sum(
    oi.quantity::numeric / greatest(coalesce(p.production_capacity_per_day,50),1)
  ),1)))::integer
  into v_days
  from public.order_items oi
  left join public.products p on p.id=oi.product_id
  where oi.order_id=p_order_id;

  update public.orders
  set estimated_completion_date = current_date + v_days,
      updated_at = now()
  where id=p_order_id and phase not in ('embalado','expedicao','entregue');
end
$$;

create or replace function private.order_item_refresh_estimate()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.refresh_order_estimate(coalesce(new.order_id,old.order_id));
  return coalesce(new,old);
end
$$;

drop trigger if exists trg_order_item_refresh_estimate on public.order_items;
create trigger trg_order_item_refresh_estimate
after insert or update or delete on public.order_items
for each row execute function private.order_item_refresh_estimate();

do $$
declare item record;
begin
  for item in select id from public.orders where deleted_at is null loop
    perform private.refresh_order_estimate(item.id);
  end loop;
end
$$;

create or replace function private.log_order_timeline()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_title text;
  v_type text;
begin
  if tg_op='INSERT' then
    v_type:='created'; v_title:='Pedido recebido';
  elsif new.phase is distinct from old.phase then
    v_type:='phase';
    v_title:=case new.phase
      when 'arte_em_criacao' then 'Criação da arte iniciada'
      when 'aguardando_aprovacao' then 'Prévia enviada para aprovação'
      when 'arte_aprovada' then 'Arte aprovada pelo cliente'
      when 'em_producao' then 'Produção iniciada'
      when 'embalado' then 'Pedido embalado e conferido'
      when 'expedicao' then 'Pedido enviado'
      when 'entregue' then 'Pedido entregue'
      else 'Fase atualizada' end;
  elsif new.quality_status is distinct from old.quality_status then
    v_type:='quality'; v_title:='Qualidade: '||replace(new.quality_status,'_',' ');
  elsif new.payment_status is distinct from old.payment_status then
    v_type:='payment'; v_title:='Pagamento: '||replace(new.payment_status,'_',' ');
  else
    return new;
  end if;

  insert into public.order_timeline(order_id,event_type,title,details,created_by)
  values(new.id,v_type,v_title,jsonb_build_object(
    'phase',new.phase,'status',new.status,'quality_status',new.quality_status,
    'shipping_status',new.shipping_status,'payment_status',new.payment_status
  ),auth.uid());
  return new;
end
$$;

drop trigger if exists trg_order_timeline on public.orders;
create trigger trg_order_timeline
after insert or update of phase,quality_status,payment_status on public.orders
for each row execute function private.log_order_timeline();

insert into public.order_timeline(order_id,event_type,title,details)
select o.id,'created','Pedido recebido',jsonb_build_object('phase',o.phase,'status',o.status)
from public.orders o
where not exists(select 1 from public.order_timeline t where t.order_id=o.id);

create or replace function public.koda_create_snapshot()
returns uuid
language plpgsql
security definer
set search_path = 'public'
as $$
declare v_id uuid; v_snapshot jsonb;
begin
  if not public.koda_has_role(array['admin']) then raise exception 'Acesso negado'; end if;
  v_snapshot := jsonb_build_object(
    'created_at', now(),
    'customers', coalesce((select jsonb_agg(to_jsonb(t)) from public.customers t), '[]'::jsonb),
    'products', coalesce((select jsonb_agg(to_jsonb(t)) from public.products t), '[]'::jsonb),
    'materials', coalesce((select jsonb_agg(to_jsonb(t)) from public.materials t), '[]'::jsonb),
    'product_materials', coalesce((select jsonb_agg(to_jsonb(t)) from public.product_materials t), '[]'::jsonb),
    'material_consumptions', coalesce((select jsonb_agg(to_jsonb(t)) from public.material_consumptions t), '[]'::jsonb),
    'orders', coalesce((select jsonb_agg(to_jsonb(t)) from public.orders t), '[]'::jsonb),
    'order_items', coalesce((select jsonb_agg(to_jsonb(t)) from public.order_items t), '[]'::jsonb),
    'order_quality_checks', coalesce((select jsonb_agg(to_jsonb(t)) from public.order_quality_checks t), '[]'::jsonb),
    'order_timeline', coalesce((select jsonb_agg(to_jsonb(t)) from public.order_timeline t), '[]'::jsonb),
    'quotes', coalesce((select jsonb_agg(to_jsonb(t)) from public.quotes t), '[]'::jsonb),
    'quote_items', coalesce((select jsonb_agg(to_jsonb(t)) from public.quote_items t), '[]'::jsonb),
    'suppliers', coalesce((select jsonb_agg(to_jsonb(t)) from public.suppliers t), '[]'::jsonb),
    'purchases', coalesce((select jsonb_agg(to_jsonb(t)) from public.purchases t), '[]'::jsonb),
    'cash_transactions', coalesce((select jsonb_agg(to_jsonb(t)) from public.cash_transactions t), '[]'::jsonb),
    'marketing_posts', coalesce((select jsonb_agg(to_jsonb(t)) from public.marketing_posts t), '[]'::jsonb),
    'bank_accounts', coalesce((select jsonb_agg(to_jsonb(t)) from public.bank_accounts t), '[]'::jsonb),
    'company_settings', coalesce((select jsonb_agg(to_jsonb(t)) from public.company_settings t), '[]'::jsonb)
  );
  insert into public.koda_backup_snapshots(created_by,snapshot) values(auth.uid(),v_snapshot) returning id into v_id;
  delete from public.koda_backup_snapshots where created_at < now() - interval '30 days';
  return v_id;
end
$$;
